# Generated by Django 4.0.2 on 2022-02-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='url',
        ),
        migrations.AddField(
            model_name='exp',
            name='gitHub',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exp',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='skills'),
        ),
        migrations.AddField(
            model_name='skills',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.RemoveField(
            model_name='projects',
            name='skills',
        ),
        migrations.AddField(
            model_name='projects',
            name='skills',
            field=models.ManyToManyField(related_name='projects', to='core.Skills'),
        ),
    ]
