# Generated by Django 4.0.2 on 2022-02-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_projects_url_exp_github_exp_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='exp',
            name='name',
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.FileField(null=True, upload_to='skills'),
        ),
    ]
