# Generated by Django 4.0.2 on 2022-03-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_exp_options_alter_formation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
