# Generated by Django 4.0.2 on 2022-05-03 14:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exp',
            old_name='team',
            new_name='my_title',
        ),
        migrations.RenameField(
            model_name='exp',
            old_name='title',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='exp',
            old_name='gitHub',
            new_name='web',
        ),
        migrations.AddField(
            model_name='exp',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='backend_gitHub',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='frontend_layout',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exp',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='exp',
            name='init_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
