# Generated by Django 4.0.2 on 2022-08-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_team_exp_my_title_rename_title_exp_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='skills',
            field=models.ManyToManyField(related_name='projects', to='core.Skills'),
        ),
    ]
