# Generated by Django 4.0.2 on 2022-08-22 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogTech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogTech.category'),
        ),
    ]
