# Generated by Django 4.0.2 on 2022-08-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('svg', models.TextField()),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='works')),
                ('live', models.URLField(blank=True, null=True)),
                ('place', models.CharField(max_length=255)),
                ('place_web', models.URLField(blank=True, null=True)),
                ('my_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('init_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('skills', models.ManyToManyField(related_name='works', to='portfolio.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='projets')),
                ('live', models.URLField(blank=True, null=True)),
                ('init_date', models.DateField()),
                ('intro', models.TextField()),
                ('description', models.TextField()),
                ('skills', models.ManyToManyField(related_name='projects', to='portfolio.Skill')),
            ],
        ),
    ]
