# Generated by Django 4.0.2 on 2022-08-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-init_date']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-init_date']},
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
